#!/usr/bin/env bash
# The `peregrine` corpus: the λ□ fixtures Peregrine's own test suite extracts
# from its Rocq and Lean programs, read where upstream leaves them
# (test/{rocq,lean}/extraction/) and consumed in place -- nothing is copied into
# this repository. With the upstream directory absent the glob matches nothing
# and the corpus prints no rows, which run.py reports as unavailable.
#
# The files are generated by upstream's `make theory` / `lake build`, so an
# upstream checkout that has not been built yet also yields no rows.
#
# `java` only: upstream ships no OCaml or C DRIVER for these fixtures (its
# runner links each one against a per-backend TypeScript harness), and our OCaml
# and C stages need a driver from a runtime/ bundle plus an attribute file, which
# would be a per-program file of exactly the kind this corpus avoids.
#
# The `expected` value comes from peregrine.expected next to this script: it is
# upstream's own recorded answer (test/src/tests.ts, `expected_output`) with each
# constructor name replaced by its declaration index, which is what our
# `Rt.Data` renderer prints. The translation is written down there by hand, one
# line per fixture with upstream's string in a comment, because it uses only
# Rocq/Lean's constructor order -- an external fact -- and must stay reviewable
# without running anything. A fixture with no line there gets no value.
#
# No row is `xfail`, and that was established by running them, not by
# assumption: all 14 pass on java (2026-08-19, upstream 247d495), including the
# six `_typed` fixtures and mutual/odd-even recursion. Upstream marks none of
# them as expected-to-fail either. Put a reason in the `xfail` column if that
# ever changes.
#
# `.tast` files are ignored by the glob: `LambdaBox.ard` models untyped λ□ only.
# The `_typed.ast` fixtures are fine -- `peregrine ast box` erases their type
# annotations on the way in.
set -euo pipefail

CORPUS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$HOME/peregrine-tool/test"
shopt -s nullglob

for ast in "$ROOT"/*/extraction/*.ast; do
  frontend=${ast#"$ROOT"/} frontend=${frontend%%/*}
  base=${ast##*/} base=${base%.ast}
  name="peregrine-$frontend-${base,,}"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$ast" \
    "$(awk -v n="$name" '$1 == n { print $2 }' "$CORPUS_DIR/peregrine.expected")" \
    "java" "" "" \
    "peregrine test/$frontend/extraction/$base.ast"
done
