#!/usr/bin/env bash
# Shared declarations for a case that runs a lean-to-lambdabox benchmark, i.e. a
# checked-in `prog.ast` whose Lean primitives are λ□ axioms. Sourced from a
# case.sh AFTER it has set ARENDMOD (the Arend module name to import the .ast as):
#
#   ARENDMOD=LeanQsort
#   . "$LEAN_OCAML_RT/lean-case.sh"
#
# It only sets variables -- everything a Lean case has in common:
#
#   * both backends read the SAME checked-in prog.ast (no per-backend
#     re-extraction), which is what makes the comparison differential;
#   * the OCaml side links Lean's own realizations of the axioms from this
#     directory (see README.md), so the two backends implement the same axioms
#     independently: ours in ToJava.ard's `javaAxioms` -> runtime/Rt.java, theirs
#     in nat.ml/int.ml/eq.ml/decidable.ml/LeanArray.ml;
#   * `bench.mli` (in the case's own directory, generated by `#erase ... mli`)
#     types the generated module, since `malfunction cmx` emits no .cmi;
#   * prog.attr is empty: an axiom is resolved by NAME here (Peregrine compiles an
#     unrealized axiom to `(global $Axioms $def__Nat_add)`), not by remapping.
#
# A case may override any of these afterwards, and must set EXPECTED and NOTE.
BACKENDS="java ocaml"

AST_PRODUCER="cat $CASE_DIR/prog.ast"
JAVA_PRODUCER="import-ast $CASE_DIR/prog.ast $ARENDMOD && extract-arend Imported.$ARENDMOD:progJava$JAVA_DEF_SUFFIX"
ATTR_OCAML_PRODUCER="cat $CASE_DIR/prog.attr"

OCAML_MODULE=bench
OCAML_DRIVER="$LEAN_OCAML_RT/bench_main.ml"
# Dependency order; `axioms.ml` is the module Peregrine's output refers to and
# just re-exports the rest. All benchmarks here return a Lean `Nat`, hence the
# single `bench_main.ml` driver.
OCAML_EXTRA="$LEAN_OCAML_RT/decidable.mli $LEAN_OCAML_RT/decidable.ml
             $LEAN_OCAML_RT/eq.mli $LEAN_OCAML_RT/eq.ml
             $LEAN_OCAML_RT/nat.mli $LEAN_OCAML_RT/nat.ml
             $LEAN_OCAML_RT/int.mli $LEAN_OCAML_RT/int.ml
             $LEAN_OCAML_RT/LeanArray.mli $LEAN_OCAML_RT/LeanArray.ml
             $LEAN_OCAML_RT/axioms.mli $LEAN_OCAML_RT/axioms.ml
             bench.mli"
# nat.ml/int.ml are Zarith-based, so the compiler must be ocamlfind's wrapper.
OCAMLOPT="ocamlfind ocamlopt"
OCAML_FLAGS="-package zarith"
OCAML_LINK_FLAGS="-linkpkg"
